config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core"),),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views as room_views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", room_views.RoomDetail.as_view(), name="detail"),
    path("search/", room_views.search, name="search"),
]

rooms/models.py
from django.db import models
from django_countries.fields import CountryField
from django.urls import reverse
from core import models as core_models
from users import models as user_models


class AbstractItem(core_models.TimeStampedModel):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """RoomType"""

    class Meta:
        ordering = ["-created"]


class Amenity(AbstractItem):

    """Amenity"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """Facility"""

    class Meta:
        verbose_name_plural = "Facilities"


class Rule(AbstractItem):

    """Rule"""

    class Meta:
        verbose_name_plural = "House Rules"


class Photo(core_models.TimeStampedModel):

    """Photo model def"""

    caption = models.CharField(max_length=150)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """ Room Model Definitions """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField(help_text="How many people will be staying?")
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)

    host = models.ForeignKey(
        user_models.User, related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    rules = models.ManyToManyField("Rule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        return 0

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

rooms/forms.py
from django import forms
from . import models
from django_countries.fields import CountryField


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    host = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

rooms/views.py
from django.views.generic import ListView, DetailView
from django.http import Http404
from django.urls import reverse
from django.utils import timezone
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django_countries import countries
from . import models, forms


class HomeView(ListView):

    model = models.Room

    paginate_by = 10
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()
        context["now"] = now
        return context


class RoomDetail(DetailView):

    model = models.Room


def search(request):

    country = request.GET.get("country")

    if country:

        # 작성한 form의 내용이 제출 후에도 value로 남아있게 합니다.
        form = forms.SearchForm(request.GET)

        # form이 에러없이 작성되었다면
        if form.is_valid():

            city = form.cleaned_data.get("city")
            country = form.cleaned_data.get("country")
            room_type = form.cleaned_data.get("room_type")
            price = form.cleaned_data.get("price")
            guests = form.cleaned_data.get("guests")
            bedrooms = form.cleaned_data.get("bedrooms")
            beds = form.cleaned_data.get("beds")
            baths = form.cleaned_data.get("baths")
            instant_book = form.cleaned_data.get("instant_book")
            host = form.cleaned_data.get("host")
            amenities = form.cleaned_data.get("amenities")
            facilities = form.cleaned_data.get("facilities")

            filter_args = {}

            if city != "Anywhere":
                filter_args["city__startswith"] = city

            filter_args["country"] = country

            if room_type is not None:
                filter_args["room_type"] = room_type

            if price is not None:
                filter_args["price__lte"] = price

            if guests is not None:
                filter_args["guests__gte"] = guests

            if bedrooms is not None:
                filter_args["guests__gte"] = bedrooms

            if beds is not None:
                filter_args["guests__gte"] = beds

            if baths is not None:
                filter_args["baths__gte"] = baths

            if instant_book is True:
                filter_args["instant_book"] = True

            if host is True:
                filter_args["host__superhost"] = True

            for amenity in amenities:
                filter_args["amenities"] = amenity

            for facility in facilities:
                filter_args["facilities"] = facility

            qs = models.Room.objects.filter(**filter_args).order_by("-created")

            paginator = Paginator(qs, 10, orphans=5)

            page = request.GET.get("page", 1)

            rooms = paginator.get_page(page)

            return render(request, "rooms/search.html", {"form": form, "rooms": rooms})
    else:
        # country 없이 처음으로 렌더될 때

        form = forms.SearchForm()

    return render(request, "rooms/search.html", {"form": form})

templates/rooms/home.html
<!-- base -->
{% extends "base.html" %}

<!-- pagename block -->
{% block page_name%} Home {% endblock page_name%}

<!-- block-->
{% block content %}
  {% for room in rooms%}
    <h2>{{room.name}} / ${{room.price}}</h2>
  {%endfor%} 

  <h5>
    {% if rooms.has_previous %}
        <a href="/?page={{rooms.number|add:"-1"}}">Previous</a>
    {% endif %}

    Page {{rooms.number}} of {{rooms.paginator.num_pages}}

    {% if rooms.has_next %}
        <a href="/?page={{rooms.number|add:"1"}}">Next</a>
    {% endif %}
  </h5>

  {% for page in rooms.paginator.page_range %}
    <a href="/?page={{page}}">{{page}}</a>
  {% endfor %}
{% endblock content %}

templates/rooms/room_detail.html
<!-- base -->
{% extends "base.html" %}

<!-- pagename block -->
{% block page_name%} Home {% endblock page_name%}

{% block content %}
    <div>
        <h1>{{room.name}}</h1>
        <h3>{{room.description}}</h3>
    </div>
    <div>
        <h2>By: {{room.host.username}}
        {% if room.host.superhost %}
            (superhost)
        {% endif %}
        </h2>
        <h3>Amenities</h3>
        <ul>
        {% for a in room.amenities.all %}
            <li>{{a}}</li>
        {% endfor %}
        </ul>
        <h3>Facility</h3>
        <ul>
        {% for a in room.facilities.all %}
            <li>{{a}}</li>
        {% endfor %}
        </ul>
        <h3>House Rules</h3>
        <ul>
        {% for a in room.rules.all %}
            <li>{{a}}</li>
        {% endfor %}
        </ul>
    </div>

{% endblock content %}

templates/rooms/room_list.html
<!-- base -->
{% extends "base.html" %}

<!-- pagename block -->
{% block page_name%} Home {% endblock page_name%}

<!-- block-->
{% block content %}

  {{now}}

  {% for room in rooms%}
    <h3>
      <a href="{% url "rooms:detail" room.pk %}">
        {{room.name}} / ${{room.price}}
      </a>
    </h3>
  {%endfor%} 

  <h5>
    {% if page_obj.has_previous %}
        <a href="/?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}

    Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

    {% if page_obj.has_next %}
        <a href="/?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}
  </h5>

  {% for page in page_obj.paginator.page_range %}
    <a href="/?page={{page}}">{{page}}</a>
  {% endfor %}
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}


{% block page_name %}
    Search
{% endblock page_name %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <h2>Search!</h2>

    <form method="get" action="{% url "rooms:search"%}">
        {{form.as_p}}
        <input type="submit" value="Search"></input>
    </form>

    <h3>Results</h3>

    {% for room in rooms %}
        <h3>{{room.name}}</h3>
    {% endfor %}

{% endblock content %}